name: opencanteen
description: Open-source mobilní aplikace pro přístup do iCanteen

publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 1.4.3+23

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  canteenlib: ^1.0.1
  flutter_secure_storage: 5.0.2
  url_launcher: ^6.0.20
  path_provider: ^2.0.9
  shared_preferences: ^2.0.13
  introduction_screen: ^3.0.1
  flutter_local_notifications: ^12.0.3+1
  timezone: ^0.9.0
  flutter_native_timezone: ^2.0.0
  intl: ^0.17.0
  package_info_plus: ^1.4.3+1
  flutter_background: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpg"
  adaptive_icon_background: "#4f4685"
  adaptive_icon_foreground: "assets/fore.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
